### PR TITLE
Layout

### PR DESCRIPTION
**Pull request by danieljustus32**
Apologies for the giant pull request, @kapunahelewong. I dropped in some vanilla bootstrap, added in a different `index.html` with just a landing page (twitter handles and avis could go here as per issue #3 as well as links to git docs as per issue #8), added navbar with a dropdown for help pages as per issue #14, and added instructions for contributing to help pages in `README.md`. 

Github's saying this one can't be automatically merged, however I'm not seeing which diffs are giving it trouble.

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Wow, very cool, @danieljustus32! Maybe I should set up gh-pages....?

It's not too big. It looks like the conflicts are in `pullrequests/index.html`. I think all you need to do is rebase. A note though, generally, you'll want to squash before trying to rebase or you can get conflicts in each commit (which can get repetitive and almost disorienting the first time it happens to you). So I'd squash first. I use on your `layout` branch:

`git rebase -i HEAD~#` 

where the `#` is the number of commits I want to squash. Then I rebase and push up. Right now, your branch is 4 commits behind master, so squashing then rebasing might sort out these conflicts. Let me know if you have any issues. Also, for what it's worth, if you're ever concerned you might wipe out your work while rebasing, it's totally ok to simply make a back up copy of the project just in case. I've done so before and so have other contributors to Angular.io while learning their way around the workflow of git.

EDIT: when squashing I `pick` the top one and `fixup` the rest, but you can do it however you like.

**Comment by danieljustus32** [comment]
Thank you so much for all the help, @kapunahelewong. I learned how to add your repository as a remote, and I think I just successfully rebased! Never done that before, so it looks like git-playground is doing its job. 😀 Anyway, everything's squashed into one commit, but then the process failed because i had deleted the `pullrequests/` directory. I just ran `git rm pullrequests/index.html` to untrack it since I had moved stuff around, and I think I got it!

Oh and I think gh-pages is a cool idea, if we wanted to get really crazy, we could even do css animations on the pages to show visually with diagrams what exactly happens when you run some of the more transparent commands, I know I tend to learn better that way.

**Comment by kapunahelewong** [comment]
Wow, @danieljustus32, well done on the squash and rebase! I have hesitated to get too fancy simply because someone new to open source might be looking for ultra simple things that they feel like they can't break. You _could_ create the animations idea in a separate repo and we could link to it as a resource. That way this repo stays super simple and you have complete control over something you will have put a lot of effort into (animated diagrams can be time consuming and a portfolio piece in their own right). The playground could be like just trying out github where an animated set of diagrams could be a nice next step for someone wanting more challenging things to try. What do you think? Also, do you want me to merge this? It looks good.

**Comment by danieljustus32** [comment]
You're right, that would be a sweet portfolio piece, and I could use some of those. I might just do something like that. But yeah, I can see where it might feel overwhelming for someone looking to start contributing. That's actually why I used cdn's and the layout file, I would normally go with node.js and a template engine and inject the layout into all views, but I didn't want it to get too complex and alienate anyone. Anyway, as for this pull request, go ahead and merge if everything looks good to you, and I may go knock out a code of conduct or add some stuff to the landing page 👍

**Comment by kapunahelewong** [comment]
Great, @danieljustus32. If you decide to make such a portfolio piece, let's make sure to link to it. And yes, your choice to use cdns was good too. Merrrrrging. :)

**Pull request merged**
