### PR TITLE
Adding some default folders in .gitignore generated automatically by IDE's

### PR DESCRIPTION
**Pull request by pedropnaves**
Was hard to choose which files to ignore in a simple HTML project.

I thought of some default folders automatically generated by IDE's.

- [X] JetBrains
- [X] Visual Studio Code

I still think we can improve. 

Any suggestion?

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Hi @pedropnaves! Thanks for updating the `.gitignore`! Would you like to continue editing or would you like me to merge? I can go either way. :)

**Comment by kapunahelewong** [comment]
Oh, PS, sometimes, on my bigger projects I use the `.gitignore` from angular. It's handy and covers probably way more than my humble projects need, but it's nice and free. So if you do want to add more, that's one example of a comprehensive working one. https://github.com/angular/angular/blob/master/.gitignore

**Comment by pedropnaves** [comment]
Hi @kapunahelewong , thanks for your review!

I appreciate your suggestion.

In my last commit, I increased .gitignore file with your suggestion.

Feel free to merge or comment again!
Thanks!

**Comment by pedropnaves** [comment]
Hi @kapunahelewong thanks for your review!

> Oh, PS, sometimes, on my bigger projects I use the `.gitignore` from angular. It's handy and covers probably way more than my humble projects need, but it's nice and free. So if you do want to add more, that's one example of a comprehensive working one. https://github.com/angular/angular/blob/master/.gitignore

I added your

**Review by kapunahelewong — APPROVED** [review]
Very nice! Thank you!!

**Pull request merged**
