### PR TITLE
Rebasing-branch: fixing typos, prettier reformat and trying out rebasing

### PR DESCRIPTION
**Pull request by sambogaert**
@kapunahelewong you can leave this branch open. I'm trying out your rebasing steps. 😊

### CODE REVIEW

**Comment by kapunahelewong** [comment]
Certainly, @sambogaert. I've just made a typo fix in `pullrequests/index.html`, so now GitHub is telling us there's a conflict. I would fix them locally with the commands I'd mentioned before (to really get an understanding of it) rather than using the `Resolve conflicts` button above. It may be of interest to note that on some big repos, the people who run them prefer the same, that is, not to use the button.

Oh! I just noticed that I edited exactly one of your edits! I didn't even mean to! I randomly picked something. But this makes it interesting because you'll get a conflict when you try rebasing - look at your terminal and it will tell you the details. When you get the error, just open the file (`pullrequests/index.html`) and scroll or search for the conflict - it'll probably be the `proompt` -> `prompt` fix. A find for `>>>` or `<<<` is usually what I do, but you could search for it however you like to find your way to the conflict. Accept the fix that I made, save your file and then head back to the command line. There, you'll tell it `git add --all`. Then, **don't commit**. Instead, do `git rebase --continue". If you've sorted out all the conflicts, it'll finish up without errors or anything strange and you'll be back at your command prompt. I hope this helps! (I really didn't mean to edit the exact same thing - but this really is what happens, so this is good!).

If your editor is Visual Studio Code (VSC), you can just click to accept. If your editor doesn't have this feature, just delete your change and keep mine. Include in your deletion the `<<<<HEAD` kind of markers. There's an opening one and a closing one. Enjoy!

**Comment by sambogaert** [comment]
Thank you @kapunahelewong for all this useful info! 😊
I tried out rebasing like you described here and on the other pull request. I had a local copy and a fork like you mentioned in the 5 steps, but I only used my fork in this case. Is this the correct approach or did I missed something? Also when everything was rebased I did a `git push -f`.

**Comment by kapunahelewong** [comment]
Sure thing, @sambogaert - it all looks good. Your fork's `master` is even with master here, and your branch is only one commit ahead. And when I look at your file that you edited here in this PR, it looks correct since it has that "proompt" fix. It could very well be that my steps were maybe too verbose (imagine that! 😁) but you managed to do it right anyway! Well done!

**Comment by kapunahelewong** [comment]
PS- if you want me to merge, I can. If you'd rather do some more rebasing, I can make some more changes. Totally up to you.

**Comment by sambogaert** [comment]
Great! 😄 You can merge it if you like. 
I’ll probably tag you if I’m trying something out 😁

**Comment by kapunahelewong** [comment]
Sounds good, @sambogaert. I'll merge. Thank you!!!

**Pull request merged**
